name: CI tests

on:

    push:

        branches:

            - main

jobs:

    test:

        runs-on: ubuntu-latest

        name: Run ESLint and Jest testing

        steps:

        - uses: actions/checkout@v3

        - uses: bahmutov/npm-install@v1

        - run: npm run lint

        - run: npm test -- --watchAll=false
